import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/navbar";
import Search from "@/components/search";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex">
        <aside>
          <Navbar />
        </aside>
        <section>{children}</section>
        <section>
          <Search />
        </section>
      </div>
    </>
  );
}
